# Generated by Django 4.2.4 on 2023-09-15 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tripCard',
            fields=[
                ('From', models.CharField(max_length=200)),
                ('To', models.CharField(max_length=200)),
                ('Date', models.DateTimeField(null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tripCompleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='alreadyBookedCard',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('alreadyInTrain', models.BooleanField(default=False)),
                ('Date', models.DateTimeField()),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
