# Generated by Django 4.2.4 on 2023-09-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alreadybookedcard',
            name='tripCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
