# Generated by Django 4.2.4 on 2023-09-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alreadybookedcard_tripcompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alreadybookedcard',
            name='name',
        ),
        migrations.AddField(
            model_name='alreadybookedcard',
            name='From',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alreadybookedcard',
            name='To',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alreadybookedcard',
            name='TrainNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alreadybookedcard',
            name='reqToJoin',
            field=models.ManyToManyField(blank=True, to='base.alreadybookedcard'),
        ),
        migrations.AddField(
            model_name='alreadybookedcard',
            name='seatInfo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tripcard',
            name='reqToJoin',
            field=models.ManyToManyField(blank=True, to='base.tripcard'),
        ),
        migrations.AlterField(
            model_name='alreadybookedcard',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripcard',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripcard',
            name='From',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tripcard',
            name='To',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
