# Generated by Django 4.2.4 on 2023-09-16 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_alreadybookedcard_name_alreadybookedcard_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tripCompleted', models.BooleanField(default=False)),
                ('alreadyBookedCardMember', models.ManyToManyField(related_name='alreadyBooked_cards', to='base.alreadybookedcard')),
                ('tripCardMember', models.ManyToManyField(related_name='trip_cards', to='base.tripcard')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
