# Generated by Django 4.2.4 on 2023-09-16 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='TravelGroup',
        ),
    ]
